### PR TITLE
Update scripts/tweet_things.py

### PR DESCRIPTION
**Pull request by mficke**

### CODE REVIEW

**Comment by stvnrlly** [comment]
Nice! Were you able to figure out a way to test this?

**Comment by mficke** [comment]
I think there's a typo in my code, actually. `document.annotation_document.body.strip()` should be `Document.annotation_document.body.strip()` (with "Document" capitalized), yes?

Couldn't quite figure out how to write a test function, any thoughts? I think we'd just need to change previous_tweets in main() to a set of test documents, some blank and some with text:
```python
def main():
    # Put test documents here 
	previous_tweets = {}

    post_document_tweet(previous_tweets)
```
and then change post_document_tweet to something like this:
```python
def post_document_tweet(previous_tweets):
	from django.utils.timezone import now

	for doc in Document.objects.filter(created__gt=now() - timedelta(days=5)).order_by('created'):
		key = "document:%d" % doc.id
		# Don't post empty documents
		if Document.annotation_document.body.strip() == "": continue
		if key in previous_tweets: continue

		print doc
```
Which would log which documents were going through and which were being passed over.

I don't know how the documents are formatted, though. How would you set up the test documents?

**Comment by stvnrlly** [comment]
My guess is that you'd want to use `doc`, as that's what's being passed to the loop. But that's why we need some tests!

This project actually doesn't have any tests yet, which is probably not a great practice and laziness on our part. I'm not very familiar with this area, so @JoshData can correct me if I'm wrong, but I believe that the proper thing to do would be to create a `tests` folder in the root and put testing scripts in there. The scripts can use something like [unittest](https://docs.python.org/2/library/unittest.html), and in this case would set up those representative test documents and check that they create the expected outcome.

That would be a separate pull request, but are you interested in giving that a shot? I'm interested in how this works and am happy to help, too.

**Comment by mficke** [comment]
Sure, I'll play around with that. Thanks for the feedback.

**Pull request closed without merging**
